#!/bin/sh
echo -n "insert GPU number:"
read gpu
echo -n "insert GPU factor:"
read gpu_factor
echo -n "insert dataset:"
read datasetname
echo -n "insert model:"
read model

if [ -z "$gpu" ]||[-z "$gpu_factor"]||[-z "$datasetname"]||[-z "$model"]
then
    echo "Dont forget insert GPU number, GPU factor and datasetname  \n"
exit
else
CUDA_VISIBLE_DEVICES=$gpu python main.py --gpu $gpu_factor --dataset $datasetname --model $model
fi

